### ISSUE TITLE
Can I use this software with SLEAP?

### ISSUE THREAD

**Issue by Banboo-glich** [mlfpm/deepof#1]
Thank you for your creative work!

Can I use this software with SLEAP?

**Comment by lucasmiranda42** [comment]
Hi, @Banboo-glich! Thank you for your interest. At the moment only DeepLabCut input is compatible, but we're aiming to add LEAP / SLEAP support in the near future.

If you upload or email me (lucas_miranda@psych.mpg.de) some mock SLEAP output, I could adapt the parser in our package to handle it :)

Best, and hope it helps!
Lucas

**Comment by Banboo-glich** [comment]
Thank you for response!

I got it. I'm looking forward to that day.

 We may ask you to convert it, so please take care of it at that time.

**Comment by lucasmiranda42** [comment]
Dear @Banboo-glich,

I know you created the issue a long time ago, but I'm happy to tell you that SLEAP integration is finally here :). You can find all the details in [this issue thread](https://github.com/mlfpm/deepof/issues/22).

Best, and hope it helps!
Lucas
