### ISSUE TITLE
[JOSS] Docker installation

### ISSUE THREAD

**Issue by edeno** [mlfpm/deepof#11]
It would be great to document what a user should do after running the docker image. For example, I tried:
```bash
root@05b17dd067c8:/# ipython
Python 3.9.14 (main, Oct  5 2022, 15:22:07) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.11.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deepof
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 import deepof

ModuleNotFoundError: No module named 'deepof'
```

xref: https://github.com/openjournals/joss-reviews/issues/5394

**Comment by lucasmiranda42** [comment]
Thank you for trying all installation methods! Indeed, one must install DeepOF after loading the docker image (either using pip or from the repo). Would you recommend editing the documentation, or adding DeepOF to the Docker image directly?

**Comment by edeno** [comment]
I would add DeepOF to the docker image directly. Might as well cut down on an additional step for the user.

**Comment by lucasmiranda42** [comment]
Perfect. Building already. Should be up in an hour or so

**Comment by lucasmiranda42** [comment]
Dear @edeno, 

I just pushed an updated Docker image with DeepOF loaded onto it, which should address the problem presented above. I'll close this issue for now, but feel free to reopen if needed, of course!

**Comment by edeno** [comment]
Okay I was able to import deepof successfully in this docker container. One question for you is would it also be beneficial to have deeplabcut in the container as well since the two libraries are dependent or is that out of scope in your mind?
