### ISSUE TITLE
[JOSS] Statement of Need - differences from existing software

### ISSUE THREAD

**Issue by edeno** [mlfpm/deepof#13]
In the manuscript, the authors state that there exist software packages that can detect behavior in both supervised and unsupervised manners. The authors then go onto state that what distinguishes *their software package* is supervised and unsupervised pipelines. Can the authors further clarify the differences here? Is it the second part the sentence that is the distinguishing factor? Are the supervised and unsupervised models different? It might be nice to have more than one sentence clarifying these differences.

xref: https://github.com/openjournals/joss-reviews/issues/5394

**Comment by lucasmiranda42** [comment]
Dear @edeno,

I have modified the text to further clarify the additions to the state of the art, and added the figure requested in the other issue to the manuscript, as I felt it could help with the description of the workflow here too.

Best, and let me know what you think!
Lucas
