### ISSUE TITLE
[JOSS] Pip installation failure (MacOS)

### ISSUE THREAD

**Issue by cellistigs** [mlfpm/deepof#14]
Hello, 

I also encountered issues with pip installation: 

```
Collecting tables==3.8.0 (from deepof)
  Downloading tables-3.8.0.tar.gz (8.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 4.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      ld: library not found for -lhdf5
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      cpuinfo failed, assuming no CPU features: 'flags'
      * Using Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11)
      * Found cython 0.29.35
      * USE_PKGCONFIG: True
      * Found conda env: ``/Users/taigaabe/miniforge3/envs/deepof``
      .. ERROR:: Could not find a local HDF5 installation.
         You may need to explicitly state where your local HDF5 headers and
         library can be found by setting the ``HDF5_DIR`` environment
         variable or by using the ``--hdf5`` command-line option.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

I am working on an M1 MacBook Air (OS Version 12.0.1). It appears this may be a known issue with MacOS and python 3.9 (https://github.com/freqtrade/freqtrade/issues/4162#issuecomment-756219646). Please let me know if you'd like me to try any specific solutions suggested in the linked thread.

**Comment by cellistigs** [comment]
Part of review for https://github.com/openjournals/joss-reviews/issues/5394

**Comment by lucasmiranda42** [comment]
Dear @cellistigs,

I spent some time trying to debug the installation via pip for Apple Silicon macOS machines, unfortunately without success. The main issue is our dependency in [Spektral](https://graphneural.network/) for graph neural networks, which itself does not allow pip installation in Apple Silicon. We've submitted a [pull request](https://github.com/danielegrattarola/spektral/pull/409) with them some time ago which was merged, but unfortunately still not incorporated into a main release. This problem should be solved when they do.

For now, I would suggest incorporating a snippet in DeepOF's documentation stating that Poetry / Docker installation is recommended for ARM Macs. What do you think?

Best, and thank you once again!
Lucas

**Comment by cellistigs** [comment]
Adding that information to the installation guide sounds great. I'll attempt an install with Poetry/Docker, and close this issue.

**Comment by lucasmiranda42** [comment]
Thanks! I added a snippet describing the issue to both README and documentation landing page :)
