### ISSUE TITLE
[JOSS] Poetry installation failure (MacOS)

### ISSUE THREAD

**Issue by cellistigs** [mlfpm/deepof#15]
Attempting to install DeepOF with poetry results in a similar issue to #14: 

  • Installing tables (3.8.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel

  ld: library not found for -lhdf5
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  cpuinfo failed, assuming no CPU features: 'flags'
  * Using Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11)
  * Found cython 0.29.35
  * USE_PKGCONFIG: True
  * Found conda env: ``/Users/taigaabe/miniforge3/envs/deepof``
  .. ERROR:: Could not find a local HDF5 installation.
     You may need to explicitly state where your local HDF5 headers and
     library can be found by setting the ``HDF5_DIR`` environment
     variable or by using the ``--hdf5`` command-line option.

  at ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/chef.py:147 in _prepare
      143│
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│
      146│             if error is not None:
    → 147│                 raise error from None
      148│
      149│             return path
      150│
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with tables (3.8.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "tables (==3.8.0)"'.

I will reattempt this installation pending a suggested fix for pip based installation.

**Comment by cellistigs** [comment]
Part of review for https://github.com/openjournals/joss-reviews/issues/5394

**Comment by lucasmiranda42** [comment]
Dear @cellistigs,

thank you for reviewing DeepOF!

I can confirm that Poetry installation works after running:

`brew install hdf5 c-blosc`
`export HDF5_DIR=/opt/homebrew/opt/hdf5`
`export BLOSC_DIR=/opt/homebrew/opt/c-blosc`

followed by the usual commands in a clean environment (tested on an M1 Macbook pro running macOS 12.6). I continue to investigate the installation via pip. Please reopen if you still have trouble :)

Best!
Lucas

**Comment by cellistigs** [comment]
Confirming that this solved my issue!
