### ISSUE TITLE
[JOSS] Interface with DLC

### ISSUE THREAD

**Issue by cellistigs** [mlfpm/deepof#17]
I have some questions about how deepof interfaces with the outputs of DLC that I do not believe are addressed in the documentation or software paper:
1. What versions of DLC is DeepOF compatible with/tested with? If the answer is all, it would be great to see that stated explicitly. 
2. What is the recommendation for usage of DLC-native post processing routines (e.g. simple smoothing, multi-animal based techniques) vs. deepof? Should a user apply both, or default to the choice of one? 
3. What portions of the code specifically will not function if a user does not have the pre-specified set of labels expected for deepof? 

Thank you.

**Comment by cellistigs** [comment]
https://github.com/openjournals/joss-reviews/issues/5394

**Comment by lucasmiranda42** [comment]
Dear @cellistigs,

thank you for your questions! Replying in order:

1) We tested DeepOF with single and multi-animal projects on DeepLabCut 2.X (up until the most recent version when writing this comment, 2.3.4). I added a statement in the README and the documentation landing page to clarify this :)

2) All experiments presented relegate preprocessing to DeepOF, ignoring DLC post-processing routines. I don't see a problem with applying both, however, but it has not been tested. Shall we clarify this in the documentation?

3) It depends. In the supervised pipeline, if key labels for certain behaviors are missing, those annotations will be skipped. In the unsupervised pipeline, graph representations (described in the corresponding tutorial) will not be available, and the user will need to rely on matrix representations alone.

Hope this helps!
Best,
Lucas

**Comment by cellistigs** [comment]
Hi Lucas- thanks for your reply, that's great. I would suggest clarifying point 2 in the documentation. Likewise, I think that point 3 would be good to have stated somewhere (I was not able to figure this out from looking at the documentation or software paper).
