### ISSUE TITLE
Tutorial stalls on Google Colab

### ISSUE THREAD

**Issue by cellistigs** [mlfpm/deepof#18]
Hello, 

When I attempt to run the tutorial `depot_preprocessing.ipynb`, the step `my_deepof_project = my_deepof_project.create(force=True)` is extremely slow (currently has been running for 30 minutes). My assumption is that this is not the intended behavior of this code: if it is, it would be good to indicate somewhere that this step can be very time consuming (I've had 2 previous timeouts of my google colab session on this step). 

<img width="874" alt="Screen Shot 2023-05-29 at 4 43 29 PM" src="https://github.com/mlfpm/deepof/assets/29405444/123ba894-ac73-483c-80bf-3c0ff081b334">

**Comment by cellistigs** [comment]
https://github.com/openjournals/joss-reviews/issues/5394

**Comment by lucasmiranda42** [comment]
The code is behaving as intended, but area computing is indeed a hotspot for potential optimization. The cell takes around 6 min to run locally on a MacBook Pro 2022, but it's indeed too slow in colab. I'll see what I can do to optimize it, and add a warning to the tutorial if I don't manage. I'll leave it open for now!
