### ISSUE TITLE
State of the field and references

### ISSUE THREAD

**Issue by cellistigs** [mlfpm/deepof#19]
I believe more thorough discussion of the state of the field (keypoint based analysis of behavioral data) is required in the accompanying paper. In particular, the following references represent significant existing work that discusses approaches for this problem, and provide code: 

Supervised approaches: 
- Task Programming ([Sun et al. 2021](https://arxiv.org/pdf/2011.13917.pdf))
- MARS ([Segalin et al. 2021](https://elifesciences.org/articles/63720))
- Additionally, I believe the text reference for SimBA should be Nilsson et al. 2020, not Ro et al. 2020. 

Unsupervised approaches: 
- B-SOiD ([Hsu et al. 2021](https://www.nature.com/articles/s41467-021-25420-x))
- Keypoint-Moseq ([Weinreb et al. 2023](https://www.biorxiv.org/content/10.1101/2023.03.16.532307v1))

Semi-supervised approaches: 
- DAART ([Whiteway et al. 2021](https://www.biorxiv.org/content/10.1101/2021.06.16.448685v1))

**Comment by cellistigs** [comment]
https://github.com/openjournals/joss-reviews/issues/5394

**Comment by lucasmiranda42** [comment]
Wonderful! Thanks for the advice. There is a much more thorough discussion on the subject in the soon-to-be-published application paper of the software, where we use it to model chronic social defeat stress, and most of these papers are cited there. I agree the discussion is too summarized here, and will expand in consequence. I'll close the issue as soon as it's done :)

**Comment by lucasmiranda42** [comment]
Dear @cellistigs,

I extended the discussion and included all mentioned packages. I believed a more extended discussion is outside the scope of the accompanying paper (so I added a citation to a review on the topic that we recently published), but let me know if you disagree! I'm happy to discuss this further if needed :)

Best, and I'll close the issue for now,
Lucas
