### ISSUE TITLE
Pretrained models not accessible

### ISSUE THREAD

**Issue by cellistigs** [mlfpm/deepof#20]
When I follow the [link](https://gitlab.mpcdf.mpg.de/lucasmir/deepof/tree/master/models) to access pretrained models, I see the message `"models" did not exist on "master"`.

**Comment by cellistigs** [comment]
https://github.com/openjournals/joss-reviews/issues/5394

**Comment by lucasmiranda42** [comment]
Dear @cellistigs,

thank you for pointing this out! The link was indeed not up to date. Pretrained models should now be accessible.

Best,
Lucas
