### ISSUE TITLE
[JOSS] Generality of this software

### ISSUE THREAD

**Issue by edeno** [mlfpm/deepof#21]
One concern I have overall is the generality of this software. In many places the body parts are hard coded and assume a top-down camera view. I know you've mentioned it a bit in the manuscript, but can you elaborate more on how you expect this to be useful to the general community given these assumptions. It would be useful if the software could at least have the potential of generalization in some of these cases.

xref: https://github.com/openjournals/joss-reviews/issues/5394

**Comment by lucasmiranda42** [comment]
Dear @edeno, 

Than you very much for your question! This is indeed an important point. The idea behind the scheme of body parts that are required is to provide annotation tools for the most common scenarios out of the box, but I agree with you that this leads to a decrease in generality. 

There are two main places where this is a problem, that could potentially be extended in the future in different ways. These are:

1) The supervised annotation pipeline, where rules and pretrained models need specific body parts to run. Here, the current implementation will skip annotations for which labels are missing (you'll just get a NaN label), but no errors should be raised. This prevents the users from having to skip the entire pipeline if just one or a few labels are missing. Extending this pipeline with alternative labels could add flexibility, but I strongly feel is out of scope at the moment. This workflow aims to be a quick annotation tool for one of the most common scenarios, "trading off ease of use for flexibility", as we put in the paper.

2) In the unsupervised pipeline, there is the option to use a graph representation that, at the moment, uses a given set of nodes. Extensions to this in particular are indeed of interest at the moment, and new labelling schemes are starting to be supported (see [this issue](https://github.com/mlfpm/deepof/issues/7)). As I agree this is a pressing issue that would potentially lead to the package being used by more people, I'm adding a new tutorial on custom labelling schemes for the unsupervised pipeline. I'll comment again when ready :)

Best, and thank you once again for taking the time to review the package!
Lucas

**Comment by lucasmiranda42** [comment]
The documentation has been modified to mention both labelling schemes supported out of the box, and a new tutorial has been added to explain how to proceed with a custom labelling scheme that does not fit with either.

I hope this addresses the issue! I'm closing it for now, but let me know if you still have concerns :)
Best, and thank you once again!
