### ISSUE TITLE
deepof.visuals.plot_heatmaps input question for setting bin_size and bin_index

### ISSUE THREAD

**Issue by joeribordes** [mlfpm/deepof#33]
Hi,

I was looking inside the API documentation to set the bin_size for the heatmaps plotting. So let's say I have a 20min video and I would like to plot the heatmap for only the first 6min, how would I set this parameter?

The input value is set to int, but it doesn't seem to simply split my dataframe as I had expected. so that if I set bin_size to "2", it would give me a video of 10min if I set bin_index to "1" and the 2nd 10min if I set bin_index to "2". 

Could you elaborate how this function works? 

It would be the best if I can somehow select what I would like to look at, e.g. I want to plot the heatmap only after 60th sec until 360th sec.

Thanks!

**Comment by lucasmiranda42** [comment]
Hi, Joeri!

Your intuition is correct, but remember that python uses 0-based indexing: the first sequence will be number zero, the following number one, etcetera. At the moment, this is the only way to index your videos out of the box, but there are dirty workarounds to filter based on the index of your tables.

For example, copying your project and slicing the tables within to keep your range of interest, and then passing this filtered object to `plot_heatmaps` should do the trick:

python
```
import copy

my_sliced_project = copy.deepcopy(my_project)
my_sliced_project._tables = {exp_name:exp_val.iloc[<your range of choice>] for exp_name, exp_val in my_sliced_project._tables.items()}

deepof.visuals.plot_heatmaps(my_sliced_project, ...)

```

Something along these lines should work! Also, as this would still be relatively easy to modify for subsequent versions of the package, I'm marking this as a first good issue to contribute.

Best!
Lucas

**Comment by NoCreativeIdeaForGoodUserName** [comment]
Hi, Joeri,

I am the new hire developing deepOF and wanted to let you know that I added the following functionality to `plot_heatmaps`:

The input arguments `bin_index` and `bin_size` now also allow for the input of a String of the format HH:MM:SS or HH:MM:SS.SS (adding milliseconds is optional). `bin_index` here denotes the starting time of your bin and `bin_size` the duration. If I wanted to only create a heatmap starting at second 2 of the video until second 5.5 I could do that entering `bin_index="00:00:02"` and `bin_size="00:00:03.5"`.

The functionality is currently in the testing pipeline and will probably be added with one of the future minor versions of deepOF.

Best regards,
Patrick

**Comment by NoCreativeIdeaForGoodUserName** [comment]
We added the previously described string format binning option for most of our plot functions. We further added binning (int and time string) for the plot_gantt function. It is available in the most recent deepof version (deepof 0.7). hence, I'll close this issue now.
