### ISSUE TITLE
polygonal arena labeling

### ISSUE THREAD

**Issue by maxcaa** [mlfpm/deepof#38]
Hello !

Thanks for this great project! I had a quick question about which part of the arena to label.
My polygonal arena is recorded from above, we can see the whole floor, however, we can't see the top of the walls  (the walls that the mice can climb). Should I label a rectangle somewhere on the walls or simply around the floor (bottom of the wall)? 

Best

**Comment by lucasmiranda42** [comment]
Hi, @maxcaa,

thank you for your interest in DeepOF! The idea is to tag the boundaries of the floor of the arena, not the top of the walls, so your videos should be fine! Feel free to post an image here is you want to cross-check, of course. DeepOF uses these boundaries both to scale your tracks across videos (assuming all experiments in your dataset were filmed on equivalent arenas) and to detect certain behaviors, such as climbing the walls.

I'll close the issue for now, but feel free to reopen if needed :)
Best,
Lucas
