### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by joeribordes** [mlfpm/deepof#4]
Hi!

I have two feature requests that may be nice to add:

1) In deepof.visuals.plot_heatmaps(), could we add a function to overlay external signals with the coordinates? (such as neural activity, for example).

2) Could we add support for videos that have varying numbers of animals? I think the current imputation implementation would not handle well animals being introduced half-way through an experiment, for example.

Thanks!
Joeri

**Comment by lucasmiranda42** [comment]
Yes! Adding to the list, we would also like to have time bin filters on the heatmap functions
