### ISSUE TITLE
Social behaviors not being marked in supervised analysis pipeline

### ISSUE THREAD

**Issue by nathanhjp** [mlfpm/deepof#40]
Hello,

I have some problems with the `supervised_annotation()` function. I have been able to train a dlc network to label 14 bodyparts in a consistent manner, and am able to create a project. I am also able to run the supervised analysis, however social behaviors (e.g. nose_2_nose) aren't labeled. Changing the maximum distance for the behaviors to 50000 (using the params strategy outlined in the other closed issue) still did not allow for the labeling of the behaviors. By looking at the video created in the deepof project with  `deepof.visuals.animate_skeleton()`, I also saw that nose_2_nose happens multiple times in the selected timeframe. 

What could be possible solutions for the problem? I would be glad to hear any suggestions. I've attached the Gantt plot that follows from the supervised pipeline to show that the behaviors aren't being labeled.

![Screenshot 2024-04-24 103546](https://github.com/mlfpm/deepof/assets/66280571/2cbc9e72-e492-40f5-8326-1851f6d816a2)

**Comment by lucasmiranda42** [comment]
Dear @nathanhjp,

Thank you for your interest in DeepOF! This looks like a problem with the `video_scale` parameter you set when starting the project, which is used to scale distances between body parts (which work as input to all the classifiers that are failing).

In [this tutorial](https://deepof.readthedocs.io/en/latest/tutorial_notebooks/deepof_preprocessing_tutorial.html#Creating-and-running-a-project) you can find all the details, but in a nutshell:

1. If you're using polygonal arena annotations, the `video_scale` parameter should be set to the length (in millimeters) of the first side of the polygon you labelled (both for full manual annotation or using automatic detection with SAM).
2. If you're using a round arena, the parameter should correspond to the diameter of the circle (also in millimeters).

Feel free to post the project creation code you used so far, as well as a video frame showcasing the arena / tagging process if you are still having trouble.

Best wishes, and thanks again for your interest!
Lucas

**Comment by nathanhjp** [comment]
Dear @lucasmiranda42,

Thank you very much for your timely response! The video_scale parameter indeed seems to have been the problem, I missed it while looking through the tutorials. Now the aforementioned behaviours are being labeled! 

Thanks again!

Nathan

**Comment by lucasmiranda42** [comment]
Wonderful to hear! Please feel free to submit more issues if any questions or problems arise.

Best, and thank you very much for your interest once again!
Lucas
