### ISSUE TITLE
Dependency Issue in Colab

### ISSUE THREAD

**Issue by erikamoore** [mlfpm/deepof#45]
Hello,

I was trying to run some of your Colab tutorials, like [this one](https://colab.research.google.com/github/lucasmiranda42/deepof/blob/master/docs/source/tutorial_notebooks/deepof_preprocessing_tutorial.ipynb#scrollTo=4d85f5bf) from your [documentation](https://deepof.readthedocs.io/en/latest/), but encountered dependency issues.

Could you please attempt to run it on your end and consider updating the dependencies as needed? 

Thank you.

**Comment by NoCreativeIdeaForGoodUserName** [comment]
Hi and thank you for your interest in deepOF. Could you please provide me with the exact errors you are getting? Which version of deepOF were you using? All dependencies are tested and updated as appropriate with each new version and we have automatic tests that ensure that the tutorials run correctly, so I suspect that what you are experiencing may be not only simple dependency issues but could be a bit more complicated.

**Comment by erikamoore** [comment]
Thank you, that helps, and I was able to get a tutorial running. Just a quick question, while DeepOF seems to have been designed for rodents, can it can be applied to other animals, as well? I am working with SLEAP files from fish.

**Comment by NoCreativeIdeaForGoodUserName** [comment]
Don't worry, we also patched the library issue with version 0.6.4 which is out now (so I will close this thread later, but wait for possible replies from you first).

If you also film your fish from above and have your tracked data in the correct format I would expect that you also could analyze fish with deepof. However, this still would be an "off-label"-use as we do currently test deepof exclusively with mouse data. From what comes to my mind, the main thing that could be a problem could be the areas. Also, you obviously could not use any pre-trained models (as they are trained with mice) and you would have to use custom labeling scheme. In the end, as far as deepof is concerned, "mice" are only a graph of some connected bodyparts. 

I am currently pretty busy with deepof 0.7, but after that I could offer to have a look at what deepof does with your fish videos specifically, if you want to share some of your videos + tables with us. In the long term we plan to expand to more different animaly anyways. You can contact me via

patrick_schlegel@psych.mpg.de

**Comment by erikamoore** [comment]
Thank you, I really appreciate it. I will likely send some fish tables + videos your way in the coming weeks. Looking forward to learning more about deepof 0.7!

**Comment by NoCreativeIdeaForGoodUserName** [comment]
I appreciate your appreciation. We will include a multi-page changelog in the release. The main changes are:

- speeding up processing
- polishing plot functions and adding some functionality
- fixing of a bunch of bugs
- improving data imputation (that's the last change I am going to include in 0.7 which I am working at right now).

I'll now proceed to close the issue.

**Comment by LynCap** [comment]
Hello, 

I'm researching rat's behavior using DeepOf and so, I've been trying to run the tutorial on Colab as well. Yet, even with the "!pip install dask==2024.5.0 / !pip install scipy==1.13.0" it still gives me incompatibility issues between different libraries versions, mostly with scipy and jax / jaxlib. Could you please guide me in what can I do to fix it? Please let me know if you need the specific error. 

Thank you in advance for your time and patience.

**Comment by NoCreativeIdeaForGoodUserName** [comment]
Hi again, since deepof 0.7 is out now these issues should be resolved. However, note that deepof 0.7 is not backwards compatible with earlier versions. Among other things, it offers faster processing and an updated data imputation. If you are not already too deep into setting up your project with the version you are using, I would suggest to use 0.7 instead.
