### ISSUE TITLE
Feature request: Use different labeling scheme for mouse bodyparts

### ISSUE THREAD

**Issue by Sere-98** [mlfpm/deepof#7]
Hi Lucas,
I opened this to suggest to adapt deepof to a different labeling scheme than the original one, as we discussed.
Here is our labeling scheme for the mice bodyparts. We have both videos with 2 mice, as well as videos with 4 (the bodyparts labeled are the same).
![image](https://user-images.githubusercontent.com/129159855/236421791-1619cb49-9bd2-4080-841d-4764af7575ce.png)

The second issue we encountered is related to the fact that the mice often disappear inside a nest, and this seems to be a problem during the inference of the occluded bodyparts.
Here is a schema of the arena we use:
![social box](https://user-images.githubusercontent.com/129159855/236422263-07c6a783-bbb6-4e1d-82c0-a29ddeba488a.png)

Here is the problem:
![image](https://user-images.githubusercontent.com/129159855/236443307-1ce3a706-b767-48f1-b653-b8fdb5005437.png)

**Comment by lucasmiranda42** [comment]
Dear Serena,

Thank you for submitting this feature request! I'll explore what the best way to implement this is, and get back to you within the week.

Best!
Lucas

**Comment by lucasmiranda42** [comment]
Dear Serena,

Happy to tell you that the latest version implements both enhancements you suggested!

On the one hand, the `Project` constructor has now a `bodypart_graph` parameter that allows you to select between "deepof_14" (the original and default graph) and "deepof_8" (a graph using the body parts you suggested, which we see are a common choice for many groups. All downstream analyses should adapt automatically. Tutorials will be updated soon to incorporate explanations on this change.

Regarding the hiding of the animals, DeepOF should now be able to recognize this without any new input on your side. There is a new reported trait in `.supervised_annotation()` that indicates when a given animal is missing. Time points where this is the case are just excluded from further analysis.

Feel free to try this and report any follow-up questions or issues! I'm closing this one for now.
Best,
Lucas
