### ISSUE TITLE
[JOSS] Author contributions

### ISSUE THREAD

**Issue by edeno** [mlfpm/deepof#8]
Regarding contribution and authorship of the JOSS paper, it seems like the first author @lucasmiranda42 has made substantial contributions to the software package, but I am unclear on the contributions of the other authors. Could you list the contributions of the other authors here?

xref: https://github.com/openjournals/joss-reviews/issues/5394

**Comment by lucasmiranda42** [comment]
Absolutely. Joeri Bordes and Mathias Schmidt contributed with the overall design and testing of the API and scope of the package. They also regularly test new features with different datasets before any new release. Benno Pütz and Bertram Müller-Myhsok contributed with knowledge on backend design, mostly. They aided substantially with developing the CI pipeline, interleaving of the different classes, and ideas behind many of the models implemented in `deepof.models`, even when I was mostly behind the keyboard.

I am happy to clarify and/or discuss in more detail, but I think all of them deserve to be in the author's list if you agree :)
